const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false
    }
  });

  mainWindow.loadFile('index.html');
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Create index.html
const fs = require('fs');

const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <title>Genny The Generator</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      height: 100vh;
      display: flex;
      flex-direction: column;
    }

    .container {
      display: flex;
      flex-direction: column;
      height: 100vh;
    }

    .output-area {
      flex: 1;
      padding: 20px;
      background-color: #f5f5f5;
      overflow-y: auto;
    }

    .editable-content {
      width: 100%;
      height: 100%;
      border: 1px solid #ddd;
      padding: 15px;
      font-family: 'Courier New', monospace;
      font-size: 14px;
      background-color: white;
      resize: none;
      outline: none;
      border-radius: 4px;
    }

    .input-section {
      height: 200px;
      display: flex;
      background-color: #fff;
      border-top: 1px solid #ddd;
    }

    .textarea-container {
      flex: 1;
      padding: 20px;
      padding-right: 10px;
    }

    .input-textarea {
      width: 100%;
      height: 100%;
      border: 1px solid #ddd;
      padding: 10px;
      font-family: Arial, sans-serif;
      font-size: 14px;
      resize: none;
      outline: none;
      border-radius: 4px;
    }

    .button-container {
      width: 120px;
      padding: 20px;
      padding-left: 10px;
      display: flex;
      align-items: flex-end;
    }

    .generate-btn {
      width: 100%;
      height: 50px;
      background-color: #4CAF50;
      color: white;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s;
    }

    .generate-btn:hover {
      background-color: #45a049;
    }

    .generate-btn:disabled {
      background-color: #cccccc;
      cursor: not-allowed;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="output-area">
      <textarea class="editable-content" id="markdownOutput" placeholder="Generated markdown will appear here..."></textarea>
    </div>

    <div class="input-section">
      <div class="textarea-container">
        <textarea class="input-textarea" id="promptInput" placeholder="Enter your prompt here..."></textarea>
      </div>

      <div class="button-container">
        <button class="generate-btn" id="generateBtn">Generate</button>
      </div>
    </div>
  </div>

  <script>
    const generateBtn = document.getElementById('generateBtn');
    const promptInput = document.getElementById('promptInput');
    const markdownOutput = document.getElementById('markdownOutput');

    generateBtn.addEventListener('click', async () => {
      const prompt = promptInput.value.trim();

      if (!prompt) {
        alert('Please enter a prompt');
        return;
      }

      generateBtn.disabled = true;
      generateBtn.textContent = 'Generating...';

      try {
        // Simulate Gemini API call - replace with actual API integration
        const response = await simulateGeminiResponse(prompt);
        markdownOutput.value = response;
      } catch (error) {
        console.error('Error generating content:', error);
        markdownOutput.value = 'Error generating content. Please try again.';
      } finally {
        generateBtn.disabled = false;
        generateBtn.textContent = 'Generate';
      }
    });

    // Simulate Gemini API response - replace with actual Gemini API integration
    async function simulateGeminiResponse(prompt) {
      return new Promise((resolve) => {
        setTimeout(() => {
          resolve(\`# Generated Markdown

## Prompt: \${prompt}

This is a simulated response from Gemini AI.

### Features:
- **Bold text** for emphasis
- *Italic text* for style
- \`Code snippets\` for technical content

### Code Example:
\\\`\\\`\\\`javascript
function example() {
  console.log("Hello from generated markdown!");
}
\\\`\\\`\\\`

### List:
1. First item
2. Second item
3. Third item

> This is a blockquote with the generated content based on your prompt.

---

*Generated by Gemini AI*\`);
        }, 1500);
      });
    }

    // Allow Ctrl+Enter to trigger generation
    promptInput.addEventListener('keydown', (e) => {
      if (e.ctrlKey && e.key === 'Enter') {
        generateBtn.click();
      }
    });
  </script>
</body>
</html>
`;

if (!fs.existsSync('index.html')) {
  fs.writeFileSync('index.html', htmlContent);
}
